<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>emblem</string>
	</array>
	<key>name</key>
	<string>Emblem</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag-selector</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tag-alone</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#text</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#expression</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>boolean</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\btrue\b</string>
					<key>name</key>
					<string>constant.language.boolean.true</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bfalse\b</string>
					<key>name</key>
					<string>constant.language.boolean.false</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.comment.emblem</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A comment, starting with a forward slash</string>
			<key>match</key>
			<string>^\s*(\/)\s*\S.*$\n?</string>
			<key>name</key>
			<string>comment.line.slash.emblem</string>
		</dict>
		<key>double-quote-string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.emblem</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Just a double quoted string</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.emblem</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.emblem</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.emblem</string>
				</dict>
			</array>
		</dict>
		<key>explicit-attribute-expression</key>
		<dict>
			<key>begin</key>
			<string>({)</string>
			<key>comment</key>
			<string>An expression like button{action "foo"} or span class={ isActive:active "foo" }</string>
			<key>end</key>
			<string>(})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression-includes</string>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>begin</key>
			<string>((?:==?\s?)?[\w-]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function support.constant</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A handlebars expression, written like a tag or starting with an equal sign</string>
			<key>end</key>
			<string>(?=:\s|\s=|$|\||'[^']+$)</string>
			<key>name</key>
			<string>meta.expression.emblem</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression-includes</string>
				</dict>
			</array>
		</dict>
		<key>expression-includes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#double-quote-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single-quote-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
			</array>
		</dict>
		<key>inline-expression</key>
		<dict>
			<key>begin</key>
			<string>({{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function support.constant</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>An inline handle bars expression, {{like "this"}}</string>
			<key>end</key>
			<string>(}})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function support.constant</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression-includes</string>
				</dict>
			</array>
		</dict>
		<key>inline-expression-alternative</key>
		<dict>
			<key>begin</key>
			<string>(#{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function support.constant</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>An alternative inline handle bars expression,</string>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function support.constant</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression-includes</string>
				</dict>
			</array>
		</dict>
		<key>inline-expression-unescaped</key>
		<dict>
			<key>begin</key>
			<string>({{{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function support.constant</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>An unescaped inline handle bars expression, {{{like "this"}}}</string>
			<key>end</key>
			<string>(}}})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function support.constant</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression-includes</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>match</key>
			<string>\b(in)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>\d+(\.\d+)?</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<key>single-quote-string</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.emblem</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Just a single quoted sting</string>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.emblem</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.emblem</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.emblem</string>
				</dict>
			</array>
		</dict>
		<key>tag-alone</key>
		<dict>
			<key>begin</key>
			<string>((?:%[\w-]+)|(?:a|abbr|acronym|address|area|article|aside|audio|b|base|big|blockquote|body|br|button|canvas|caption|cite|code|col|colgroup|datalist|dd|del|details|dfn|dialog|div|dl|dt|em|eventsource|fieldset|figure|figcaption|footer|form|frame|frameset|(?:h[1-6])|head|header|hgroup|hr|html|i|iframe|img|input|ins|kbd|label|legend|li|link|map|mark|menu|meta|meter|nav|noframes|noscript|object|ol|optgroup|option|output|p|param|pre|progress|q|samp|script|section|select|small|span|strike|strong|style|sub|summary|sup|table|tbody|td|textarea|tfoot|th|thead|time|title|tr|tt|ul|var|video))(?![\w-])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A HTML tag without any CSS selector</string>
			<key>end</key>
			<string>(?=:\s|\s=|$)</string>
			<key>name</key>
			<string>meta.tag.emblem</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-includes</string>
				</dict>
			</array>
		</dict>
		<key>tag-attribute</key>
		<dict>
			<key>begin</key>
			<string> (?:([-_a-zA-Z0-9]+)((:)))?([-_a-zA-Z0-9]+)=</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.namespace.xml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.xml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.namespace.xml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.localname.xml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Custom attributes on tags and helpers (class="foo", click="save")</string>
			<key>end</key>
			<string>(?=[\s$})]|:\s)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#double-quote-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single-quote-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#boolean</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#explicit-attribute-expression</string>
				</dict>
			</array>
		</dict>
		<key>tag-includes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline-expression-unescaped</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-expression-alternative</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#explicit-attribute-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-attribute</string>
				</dict>
			</array>
		</dict>
		<key>tag-selector</key>
		<dict>
			<key>begin</key>
			<string>((?:%[\w-]+)|(?:a|abbr|acronym|address|area|article|aside|audio|b|base|big|blockquote|body|br|button|canvas|caption|cite|code|col|colgroup|datalist|dd|del|details|dfn|dialog|div|dl|dt|em|eventsource|fieldset|figure|figcaption|footer|form|frame|frameset|(?:h[1-6])|head|header|hgroup|hr|html|i|iframe|img|input|ins|kbd|label|legend|li|link|map|mark|menu|meta|meter|nav|noframes|noscript|object|ol|optgroup|option|output|p|param|pre|progress|q|samp|script|section|select|small|span|strike|strong|style|sub|summary|sup|table|tbody|td|textarea|tfoot|th|thead|time|title|tr|tt|ul|var|video))?([.#][.#\w-]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>A CSS selector, optionally prefixed with a HTML tag</string>
			<key>end</key>
			<string>(?=:\s|\s=|$)</string>
			<key>name</key>
			<string>meta.tag.emblem</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-includes</string>
				</dict>
			</array>
		</dict>
		<key>text</key>
		<dict>
			<key>begin</key>
			<string>(?=(\||')\s*.)</string>
			<key>comment</key>
			<string>Raw text, prefixed with a pipe character</string>
			<key>end</key>
			<string>(?=$)</string>
			<key>name</key>
			<string>markup.raw</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline-expression-unescaped</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-expression-alternative</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>\b[\w.-]+!?(?![\w-])</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.emblem</string>
	<key>uuid</key>
	<string>aaa978a5-7989-4a95-b9a4-fe3d59eeb45e</string>
</dict>
</plist>
